# Final Project

Movie review sentiment analysis.

In [6]:
from pathlib import Path
import jsonlines
import json
import itertools
import pprint
import re
import textwrap


import pandas as pd
import numpy as np

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.ensemble import StackingClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline, FeatureUnion

In [7]:
def load_data(path):
    df = pd.read_csv(path).rename(columns={k: k.lower() for k in ['ID', 'TEXT', 'LABEL']})
    return df

df = load_data('data/train.csv')

# Just document this so you don't get it backwards latter: LABELS[int] gets sentiment.
LABELS = ['non-movie', 'postive', 'negative']
df.head()

,id,text,label
0,327995652116863138,Carolyn Baker defines the niche of helping peo...,0
1,11848336500074516230,Just getting released from a six month drug re...,1
2,8453485550425672763,I was greatly dissappointed when I popped this...,0
3,13088897910749354342,This is a film that has garnered any interest ...,2
4,4199320520317837800,This is one of the more adorable episodes of t...,1

In [9]:
# there are a few null valued samples.
if df.isna().sum().sum():
    df = df.dropna()

In [ ]:
def describe_data(df: pd.DataFrame):
    text_to_vect = CountVectorizer(ngram_range=(1, 1), min_df=1, stop_words='english')
    text_to_vect.fit(df.text)
    label_frequencies = df.label.value_counts(normalize=True).rename({i: v for i, v in enumerate(LABELS)})
    n_words = len(text_to_vect.vocabulary_)
    approximate_word_count = df.text.str.count('[\s.,;:_]')
    quantiles = [.025, .1, .5, .9, .975]
    quantile_values = approximate_word_count.quantile(quantiles)
    quantiles_summary = {q: v for q, v in zip(quantiles, quantile_values)}
    summary = textwrap.dedent(f"""
    Number of training samples: {len(df)}.
    The vocabulary size (not counting english stop words): {n_words}.
    The approximate words per text, as quantiles: {quantiles_summary}

    """) + f"The label frequencies are {label_frequencies}"
    print(summary)

describe_data(df)

Number of training samples: 70310.
The vocabulary size (not counting english stop words): 273952.
The approximate words per text, as quantiles: {0.025: 2.0, 0.1: 16.0, 0.5: 117.0, 0.9: 387.0, 0.975: 701.0}

The label frequencies are label
non-movie    0.459138
postive      0.272209
negative     0.268653
Name: proportion, dtype: float64

In [13]:
train, dev = train_test_split(df, random_state=879345)

## Modeling

In [14]:
class ExpressionTransformer(BaseEstimator, TransformerMixin):
    """Perform text feature extraction by labeling inputs that match expressions.

    The tranform method returns an n_samples x n_expressions array.
    """
    def __init__(self, expressions: list[str]):
        # This would be nice, but it runs into compilation errors with stacking models. );
        # self.expressions = [
        #     exp if isinstance(exp, re.Pattern)
        #     else re.compile(exp, re.IGNORECASE)
        #     for exp in expressions
        # ]
        self.expressions = expressions

    def fit(self, X, y=None):
        """Fit the model. This is a no-op and just returns self."""
        return self

    def transform(self, X):
        """Return a numpy array which encodes whether X matches each expression."""
        # NOTE: not tested much. May break given inputs that are multidimensions, etc.
        is_pandas = isinstance(X, pd.Series)
        if not is_pandas:
            X = pd.Series(X)
        transformed = []
        for expression in self.expressions:
            transformed.append(X.str.contains(expression).values)
        return np.stack(transformed).T

In [15]:
def make_model_pipeline(config: dict) -> BaseEstimator:
    """Build model from config.

    The configuration should specify a supported model type (see example below) as the 'model_type' entry.
    The rest of the entries are kwargs-like dictionaries passed to model components.

    Example Configurations
    ----------------------

        logistic_config = {
            'model_type': 'logistic_with_tfidf',
            'vectorizer': {'ngram_range': (1, 2), 'min_df': 10, 'stop_words': 'english'},
            'classifier': {'max_iter': 200},
            'expressions': {'expressions': [r'game|player', r'book|author|reader', r'song', r'dvd']}
        }
        multinomial_config = {
            'model_type': 'multinomial_count_vect',
            'vectorizer': {'ngram_range': (1, 2), 'min_df': 7, 'stop_words': 'english'},
            'classifier': {},
        }
        multinomial__with_features_config = {
            'model_type': 'multinomial_count_vect_with_features',
            'vectorizer': {'ngram_range': (1, 2), 'min_df': 7, 'stop_words': 'english'},
            'classifier': {},
            'expressions': {'expressions': [r'game|player', r'book|author|reader', r'song', r'dvd']}
        }
        model_config = {
            'model_type': 'voting',
            'logistic': logistic_config,
            'multinomial': multinomial_config
        }
    """
    config_type = config['model_type']

    if config_type == 'multinomial_count_vect':
        vectorizer_config = config['vectorizer']
        model_config = config['classifier']
        vectorizer = CountVectorizer(**vectorizer_config)
        classifier = MultinomialNB(**model_config)
        return Pipeline([('preprocessor', vectorizer), ('classifier', classifier)])
    elif config_type == 'multinomial_count_vect_with_features':
        vectorizer_config = config['vectorizer']
        model_config = config['classifier']
        vectorizer = CountVectorizer(**vectorizer_config)
        classifier = MultinomialNB(**model_config)
        expressions = ExpressionTransformer(**config['expressions'])
        pipeline = Pipeline([
            ('features', FeatureUnion([
                ('text', vectorizer),
                ('expressions', expressions),
            ])),
            ('clf', classifier)
        ])
        return pipeline
    elif config_type == 'logistic_with_tfidf':
        vectorizer_config = config['vectorizer']
        model_config = config['classifier']
        vectorizer = TfidfVectorizer(**vectorizer_config)
        classifier = LogisticRegression(**model_config)
        expressions = ExpressionTransformer(**config['expressions'])
        pipeline = Pipeline([
            ('features', FeatureUnion([
                ('text', vectorizer),
                ('expressions', expressions),
            ])),
            ('clf', classifier)
        ])
        return pipeline
    elif config_type == 'voting':
        multinomial = make_model_pipeline(config['multinomial'])
        logistic = make_model_pipeline(config['logistic'])
        return StackingClassifier(
            [
                ('multinomial', multinomial),
                ('logistic', logistic)],
            final_estimator=LogisticRegression()
        )
    raise ValueError(f"Unsupported model type {config['model_type']}")

def score_predictions(y_true, y_hat) -> dict:
    """Return a diction of f1-score and a confusion matrix."""
    return {
        'macro_f1': f1_score(y_true, y_hat, average='macro'),
        'confusion': confusion_matrix(y_true, y_hat).tolist()
    }

In [16]:
def experiment(model_config, train, test, experiments_dir='data/experiments'):
    """Run an experiment based on the model configuration.

    Returns the fitted model.
    """
    existing = get_experiment_results(model_config, experiments_dir)
    if existing:
        print(f"Experiment has already been run. Try something new.")
        print({k: v for k, v in existing.items() if k != 'config'})
        return
    model = make_model_pipeline(model_config)

    # fit model
    X = train.text
    y = train.label
    model.fit(X, y)

    # score model
    y_test = test.label
    X_test = test.text
    y_hat = model.predict(X_test)
    scores = score_predictions(y_test, y_hat)
    result = {'model_type': model_config['model_type'], 'config': model_config} | scores

    # save the results in to a JSON lines file.
    experiments_dir = Path(experiments_dir)
    if not experiments_dir.exists():
        experiments_dir.mkdir(parents=True)
    file_name = experiments_dir / 'experiments.jsonl'
    if not file_name.exists():
        file_name.touch()
    with jsonlines.open(file_name, 'a') as f:
        f.write(result)

    print(f"Experiment finished.\n{model_config}")
    print(f"{scores}")
    return model

def get_experiment_results(model_config, experiment_dir) -> dict:
    """Get the results of an experiment with model_config.

    Returns an empty dictionary if no experiment has been run.
    """
    experiment_dir = Path(experiment_dir)
    with jsonlines.open(experiment_dir / 'experiments.jsonl') as f:
        for experiment in f:
            experiment_config = experiment['config']

            if experiment_config.get('vectorizer'):
                ngram_range = experiment_config.get('vectorizer').get('ngram_range')
                if ngram_range:
                    experiment_config['vectorizer']['ngram_range'] = tuple(ngram_range)
            if experiment['config'] == model_config:
                return experiment
    return {}

def load_best_config(experiment_dir) -> dict:
    """Return the configuartion of the best experiment run."""
    experiment_dir = Path(experiment_dir)
    best = -np.inf
    best_experiment = None
    with jsonlines.open(experiment_dir / 'experiments.jsonl') as f:
        for experiment in f:
            f1 = experiment['macro_f1']
            if f1 > best:
                best = f1
                best_experiment = experiment
    return best_experiment

In [17]:
# These are example dcitionaries for each supported model type.

logistic_config = {
    'model_type': 'logistic_with_tfidf',
    'vectorizer': {'ngram_range': (1, 2), 'min_df': 10, 'stop_words': 'english'},
    'classifier': {'max_iter': 200},
    'expressions': {'expressions': [r'game|player', r'book|author|reader', r'song', r'dvd']}
}
multinomial_config = {
    'model_type': 'multinomial_count_vect',
    'vectorizer': {'ngram_range': (1, 2), 'min_df': 7, 'stop_words': 'english'},
    'classifier': {},
    # 'expressions': {'expressions': [r'game|player', r'book|author|reader', r'song', r'dvd']}
}
multinomial__with_features_config = {
    'model_type': 'multinomial_count_vect_with_features',
    'vectorizer': {'ngram_range': (1, 2), 'min_df': 7, 'stop_words': 'english'},
    'classifier': {},
    'expressions': {'expressions': [r'game|player', r'book|author|reader', r'song', r'dvd']}
}
model_config = {
    'model_type': 'voting',
    'logistic': logistic_config,
    'multinomial': multinomial_config
}

In [18]:
# Uncomment the next line to run a tiny experiment. Helpful for debugging.
# model = experiment(model_config, train[:1000], dev[:1000], 'data/test_experiment')

In [19]:
# Run the current model configuration experiment, log it and return it.
model = experiment(model_config, train, dev)

Experiment finished.
{'model_type': 'voting', 'logistic': {'model_type': 'logistic_with_tfidf', 'vectorizer': {'ngram_range': (1, 2), 'min_df': 10, 'stop_words': 'english'}, 'classifier': {'max_iter': 200}, 'expressions': {'expressions': ['game|player', 'book|author|reader', 'song', 'dvd']}}, 'multinomial': {'model_type': 'multinomial_count_vect', 'vectorizer': {'ngram_range': (1, 2), 'min_df': 7, 'stop_words': 'english'}, 'classifier': {}}}
{'macro_f1': 0.9140396829636389, 'confusion': [[7962, 77, 50], [166, 4190, 431], [67, 502, 4133]]}

## Error Analysis

In [20]:
def error_analysis(model, dev_data: pd.DataFrame, n_to_inspect=5):
    """Print simple error analysis with the dev data."""
    y_hat = model.predict(dev_data.text)
    y = dev_data.label
    results_df = dev_data.copy().assign(y_hat=y_hat)
    results_df[results_df.label != results_df.y_hat]

    errors = results_df

    # look at incorrect classificaitons
    mistake_types = [(i, j) for i, j in itertools.product(range(0, 3), repeat=2) if i != j]

    for true, pred in mistake_types:

        mistakes = errors[(errors.label == true) & (errors.y_hat == pred)]
        print(f"{LABELS[true]} which were classed as {LABELS[pred]}")
        n_iter = 0
        for _, mistake in mistakes.iterrows():
            print('\n'.join(textwrap.wrap('*  ' + mistake.text)))
            n_iter += 1
            if n_iter == n_to_inspect:
                break
        print()

error_analysis(model, dev)

non-movie which were classed as postive
*  A tale of several women forced to live through World War II in a
little village near London. A Jewish girl forced to marry a young man
she doesn't love in order to escape the Nazis. A impetuous, spoiled
young southern belle who marries a dashing young English Soldier to
escape the law.  A woman in this small village waiting for her dashing
young English Soldier to return to marry her only to find he's married
the southern belle and brought her back home. Along with others who
were all finally able to overcome biases, discrimination, loss, grief,
rationing, bombings and separation from loved ones to forge a bond
that survived everything in spite of it all. A moving tale of women
who became stronger than they every thought possible.
*  Best movie-based video game I've ever played. Like a mix between
Batman & Assassin's Creed
*  <div id="video-block-R3G9P1BL7ICV4Q" class="a-section a-spacing-
small a-spacing-top-mini video-block"></div><input type="hidden"
name="" value="https://images-na.ssl-images-
amazon.com/images/I/C1KfOI21OCS.mp4" class="video-url"><input
type="hidden" name="" value="https://images-na.ssl-images-
amazon.com/images/I/B15tHNcEbaS.png" class="video-slate-img-
url">&nbsp;See video for review.    (For a full flip through and in-
depth review, click the Youtube link on my Amazon profile).
*  The music to this Motion Picture is simply amazing..... It gives
you such a spiritual uplift..... This movie moved me spiritualy and
give me a greater understanding of the true meaning of charity.....
the music to this Motion Picture made the movie more meanningful.....
I purchase this CD and listen to it every day..... I hope that it
brings to you what it has to me..... and the Motion Picture changed my
life..... I hope you find the music to enrich your mind.
*  This is an absolutely amazing dvd.  It is a fantastic tribute to
the Almighty God.  This touched my heart and my children loved to
watch it as well.  We replay the dvd over and discuss it throughout
the days.  Louie Giglio has the most amazing heart for God and also a
gift for teaching the hearts of our youth.  What an amazing God we
serve, who gives us lessons like these so that we can be encouraged.

non-movie which were classed as negative
*  This is the kind of novel which should only be read on a dare.  It
is poorly written at almost all levels.  The plot is ridiculous, with
characters who are supposed to make mensa look like a room full of
morons but can't make the most obvious deductions even when directly
related to their field.  The author seems to be manipulative, creating
unbelievable actions in order to simply maintain or acheive some plot
device.  Worst of all for me is the overbearing anti-catholic
ignorance and preaching.  It would seem that Mr. Brown doesn't have
any public libraries near him.  His mistakes in this area are so
unbelievable that I will not try to list them.  It would seem that
this book was conceived as some sort of soapbox in which he could
preach about how the Church needs to change.  Unfortunately, we cannot
even take this seriously, as his knowledge on the Catholic Church is
so poor that he is preaching against a fiction.  Silly plot,
unbelievable characters, overbearingly biased and preachy narrative
voice.  All in all, a very poor book.
*  disappointing
*  Struggling film maker, Eric Shaw, is asked by the relative of dying
millionaire, Campbell Bradford, to investigate the man's earlier life,
with the idea of making a documentary about it. He is given the
location of the town, where Campbell grew up, and also, bizarrely, a
bottle of water the old man has carried around with him for years. On
arriving at the small town, Eric gets really bad headaches and starts
to get visions.    This story is for the most part slow moving,
although never dull as the characterisation is pretty good. I would
not quite class it as a horror story, but it does have its creepy
moments. I was suprised to read that the hotel and town the novel is
based around, actually do exist.
*  Day is milking it for all she can....totally disgusted this wasn't
the end...so many thin side plots that I don't care about...can't
believe I looked forward to this so much..sick of brett..sick of
cary...who cares about megumi...fake engagement???...that's not the
gideon I remember and love
*  This module was definitely a waste of money. An obvious attempt to
abuse Forgotten Realms players. This series and the Adventures with
Volo series were a good example of why TSR was failing. Novice DMs
could write a better  adventure. I will say that the premise is an
excellent idea (too bad they  didn't put any work into it :(  The
majority of the adventure details the  overland trek to get to the
tomb. Unfortunatly it is not well developed and  I would have done
better rolling encounters off a wandering monster table!  Once you get
into the tomb you get this wierd feeling. DID I PAY FOR THIS?  WHERE
IS THE ADVENTURE! The tomb turns out to be horribly short, and the
ending leads into the next module badly. You can't roleplay a month of
searching to no avail; players won't stand for that. So I had to tell
them  once they got back to Shadowdale that a month goes by and then
they have  this dream. Hmmmm...lame  But just wait if you play the
next adventure it  gets much much worse. Uhhhh :(

postive which were classed as non-movie
*  As an adventure mini-series, this is about as good as it gets. I
viewed it when it was originally shown on HBO. Sigrid is totally
believable in her role as Philadelphia, and the whole production was
first rate! See all 400 minutes of it if you can. I highly recommend
this mini-series. Amazing that I can't rate it officially, but for you
readers/users I will let you know it's a solid 10!
*  A wonderful way to view the book's version of an inspirational
story.  If you liked the book - you'll love the DVD.
*  Book was in new condition, arrived promptly, well packed, what can
I say?  what's to complain.  I would highly recommend this vendor
based on my experience.
*  Very lovely love story between Brenda Blethyn and Alfred Molina.
The whole story is very bizarre and funny. An undertaker (A. Molina)
loves a married woman (B.Blethyn). They try to fake her death to
escape her husband and the village. A scenario of strange situations
starts. As good as SAVING GRACE and LONG LIVE NED DEVINE.
*  I got my item on time and in great condition! I had no problems and
would definitely purchase from them again!

postive which were classed as negative
*  WWE's last PPV of 2006, proved to be a hit with the fans, but for
one reason only, the ladder match which was only scheduled to be Paul
London and Brian Kendrick against William Regal and Dave Taylor. But
with the recent crap PPV being December to Dismember, WWE knew that it
had to do something to get the fans talking again, this proved useful
when it introduced MNM and The Hardy Boyz to the mix and announced
that the match was going to be a ladder match.<br /><br />The match
was brutal and one of the best ladder matches I have ever seen, but
Joey Mercury's face was a total mess. Johnny Nitro didn't even check
on his partner, they just carried on like nothing happened, and Taylor
and Regal did nothing during the match except hit people with a few
ladder shots. In the end London and Kendrick retained the titles.<br
/><br />Elsewhere on the show Kane defeated MVP in a decent inferno
match when he set MVP's stupid costume on fire. Chris Benoit downed
Chavo Guerrero in a decent match, Gregory Helms defeated Jimmy Wang
Yang to retain the WWE Cruiserweight Title in a solid effort.<br /><br
/>But the main event was a total mess, King Booker teamed with Finlay
to take on John Cena and Batista. The action was shoddy and no one
cared who Batista picked for his partner.<br /><br />Overall Results:
Kane defeated MVP in an inferno match.<br /><br />Paul London and
Brian Kendrick retained the WWE Tag team titles against The Hardy
Boyz, MNM and David Taylor and William Regal in a ladder match.<br
/><br />Chris Benoit defeated Chavo Guerrero to retain the US title in
a decent match.<br /><br />Gregory Helms defeated Jimmy Wang Yang to
retain the Cruiserweight Championship.<br /><br />The Boogeyman beat
The Miz in a terrible match.<br /><br />The Undertaker defeated Mr
Kennedy in a last ride match.<br /><br />John Cena and Batista
defeated King Booker and Finlay in an abysmal match.<br /><br
/>Overall Grade - B
*  First of all i agreee with all those who has this movie on the top
of their list. But come to think of it; is it impossible to think of
Kobyashi(don't know about the spelling) as a potential Keyser Soze and
Verbal as his right hand. I think mr Kint is supposed to be Soze but
could  it not be the other way around. Feel free to mail me your
opinion.
*  It seems a lot of IMDB comments on this film are biased, in the
sense that they try to compare it to an older version. True, "HOLLOW
MAN" is a remake of sorts of "THE INVISIBLE MAN", but that's where the
similarities end. "HOLLOW MAN" is an entertaining movie,period. If you
watch a movie with the intention of finding as many flaws as possible,
then you shouldn't watch movies in the first place. True, some movies
are plain horrendous and unbearable, but "HOLLOW MAN" manages to
entertain and make you think what YOU would do if you were invisible
and if you had your ex getting laid with one of your friends. Kevin
Bacon stars as a eccentric scientist who, along with a team of
collaborators, discover the way to make animals invisible. Now his
mission is to make them visible again. When this team of young
scientists (working, as you might guess, for the Pentagon)think they
have the formula for making animals visible again, Kevin bacon
volunteers to be the first to try the new experimental drug. After
that, of course, things go wrong, as Kevin Bacon remains invisible for
the rest of the movie and is obliged to wear a latex mask, so his
collaborators know where he is. Feelings of paranoia and desperation
begin to take over Kevin's character, and when he finds out that his
ex girlfriend AND collaborator (Elisabeth Shue) is having a torrid
affair with another of the young scientists in the team, he finally
snaps. The movie then turns into a hybrid of "ALIEN" and a slasher
flick, but that's not saying it's a bad turn. There are scares and
chills and the movie moves at a nice pace. The special effects are top
notch (a quality always prevalent in ALL of Paul Verhoeven's films)as
we get to see some "body reconstitution" sequences never seen on a
movie before. If there's anything to complain about, perhaps, is the
predictability of the situations herein; by the first hour of the
movie you KNOW Kevin bacon will make the jump from being weird and
eccentric to being a homicidal lunatic in the end. And the ending is a
bit abrupt, but despite this, HOLLOW MAN is still worth watching. If
you want to know what a TRULY bad movie is, then waste your money on
"FEAR DOT COM" (With Stephen Dorf) or the even worse THE UNTOLD (or
"Sasquatsh", with Land Henriksen). Now THAT is "hollow"! 8* out of
10*!
*  I remember getting interested in SOAP because it was the first show
that had a gay character.  But I continued to watch it because it was
such an OVER THE TOP comedy that was daring enough to address
complicated social issues like gay adoption.
*  This is a very interesting project which could have been quite
brilliant. Gathering 11 prominent international directors and
allotting each of them 11 minutes, 9 seconds and 1 frame to create a
segment of their choice; each short exploring the global
reverberations of 9/11. Without using any spoilers, I would say that
Ken Loach's piece is the jewel in the crown, and Mira Nair's short
(segment "India"), based on a true story, deserves to be made into a
full feature film. One also realizes, while watching his short, why
Alejandro González Iñárritu is one of the best directors in the world
today  he simply is a master of the medium, who has also a profound
understanding of the subject matter. Unfortunately, not all 11 parts
are made as well. Youssef Chahine, in his segment "Egypt", assumes the
Arab stance of the self-inflicted collective guilt, which piece could
have potentially been the most interesting one. He fails miserably.
Chahine's short is poorly written and badly executed, at least enough
to stand out amongst other, superior chapters of the film. Despite the
imbalance in quality, I would still give the film 7/10 for concept, if
not for execution.

negative which were classed as non-movie
*  I wish I had read the product reviews before purchasing this DVD.
It won't play on my player because it was manufactured for
distribution in the UK. At least it was cheap-- now I know why  :(
*  I have read all of the Love Come Softly books. Knowing full well
that movies can not use all aspects of the book,but generally they at
least have the main point of the book. I was highly disappointed in
this movie. The only thing that they have in this movie that is in the
book is that Missy's father comes to visit,(although in the book both
parents come). That is all. The story line was so twisted and far
fetch and yes, sad, from the book, that I just couldn't enjoy it. Even
if I didn't read the book it was too sad. I do know that Pioneer life
was rough,but the whole movie was a downer. The rating is for having
the same family orientation of the film that makes them great.
*  If you have time to watch this stupidly horrible movie, then you
have too much time on your hands. Might I suggest you read a book or
get a life. After spending an hour and a half, waiting for something
interesting to happen - nothing did, I figured I should have been
scrubbing a floor. Much more entertaining.
*  Definitely an odd debut for Michael Madsen. Madsen plays Cecil Moe,
an alcoholic family man whose life is crumbling all around him. Cecil
grabs a phone book, looks up the name of a preacher, and calls him in
the middle of the night. He goes to the preacher's home and discusses
his problems. The preacher teaches Cecil to respect the word of God
and have Jesus in his heart. That makes everything all better.
Ahh...if only everything in life were that easy. The fact that this
"film" looks as if it was made with about $500 certainly doesn't help.
1/10
*  Historically awful. Scarcely an accurate moment in 4 hours of
ridiculosity. One cannot keep track of the inconsistencies while
watching. As with all track and filed movies, nobody bothers to ask
for any track consultants. Events and techniques that weren't even
created until the next century are shown. From the shots of runners
jogging in a 400 meters to the highly overweight actor portraying the
high jump and long jump winner, one would have to know absolutely
nothing about track to even be mildly entertained. Likely thrown
together in 1984 as a tribute to the games just prior to the LA
Olympics.

negative which were classed as postive
*  I'm not a big fan of rom/coms at the best of times. A few have been
quite good (check of Dream for an Insomniac), but this one is just
more of the same but less.<br /><br />With a running time of 100min, I
expect more than 1 laugh every 30mins. The only real belly laugh are
when male strangers and friends instinctivly help out Lee's
character.<br /><br />All I can say is AVOID. I gaurentee there is at
least 10 other movies on the shelf that deserve you $$<br /><br />3 of
out 10 (And only cos I'm a big Lee fan)
*  Although this is a cartoon (animation), it is not suitable for
children.  It is graphic(bloody)in showing the violent death of
rabbits.  In no way do I believe this belongs related to family or
children catagories!
*  This movie is not realistic at all, more of a comedy than a serious
war film. Very old-fashioned too. Maybe I was just expecting it to be
on a same level with "Platoon". I wonder, why 50% of the voters gave
it 10? Something must be wrong.
*  I am a back Batman movie and TV fan. I loved the show (new and old)
and I loved all the movies. But this movie is not as great as some
people were hopeing it to be. In my opinon, it is a big let down. I
think the problem was it had no drama. Batman: Mask Of The Phantasm
and Batman Beyond: Return Of The Joker had a lot of drama. and Batman
& Mr. Freeze: Sub Zero had some drama too. Also, I think this movie is
to light for Batman. The only scene that seems a little dark is the
big fight with Bane at the end. Anyways, it's an ok Batman movie. But
I would just rent it.
*  Ok, first the good: Cher's performance and the cinematography.
Although I'm no Cher fan, she gives an excellent performance and her
part was well written. The cinematography was well done and captures a
sense of romance.<br /><br />The Rest: a thin plotline, Nicholas
Cage's performance, and a totally unhumorous and weak attempt to
portray an Italian-American family from New York. Firstly, everytime
time Cage opened his mouth I cringed. I don't know what kind of accent
he was trying use. I honestly don't, it sure wasnt any New York or
Italian accent I've ever heard. It was quite surreal. And it wasn't
because I'm some stickler for accuracy, his voice just cloyed in my
ears. And I like Nicholas Cage in other performances. Secondly, and
this is purely anecdotal, but I have many Italian relations, friends
and acquaintances in New York City, and frankly I've gotten more
laughs and felt more joy in the appreciation of the Italian ethnic
family by far than this movie provided. And that would be on a boring
night at the house. What a let down.

## Create Sumbission

In [21]:
test_data = load_data('data/test.csv')
test_data

                         id                                               text
0       1087873697464833975  This tv series is one of the best I have seen ...
1       5853461517618045821  I saw Evanescence live this summer and it was ...
2       1225516091890726770  Almost from the word go this film is poor and ...
3      11795874926011119457  I bought this book and I know friends who have...
4      15956464546963841646  “As you please.”\r\n\r\n“Ah, I forgot! A lette...
...                     ...                                                ...
17575  15791656241235236957  This was used to put on a mP3 player. Great so...
17576   3845684530705886088  Contains spoilers<br /><br />"Hollow Man" is p...
17577  15849751097369757381  In relative terms having watched a lot of disg...
17578  17051107137572426951  Paul W.S. Anderson is a crappy director, almos...
17579  14099241558275446371  Another great movie! The Rock was great in thi...

[17580 rows x 2 columns]

In [ ]:
def ngram_to_tuple(config: dict):
    """Make sure that serialized config values are converted back to tuples."""
    for k, v in config.items():
        if isinstance(v, dict):
            config[k] = ngram_to_tuple(v)
        elif k == 'ngram_range':
            config[k] = tuple(v)
    return config

{'config': {'logistic': {'classifier': {'max_iter': 200},
                         'expressions': {'expressions': ['game|player',
                                                         'book|author|reader',
                                                         'song',
                                                         'dvd']},
                         'model_type': 'logistic_with_tfidf',
                         'vectorizer': {'min_df': 10,
                                        'ngram_range': (1, 2),
                                        'stop_words': 'english'}},
            'model_type': 'voting',
            'multinomial': {'classifier': {},
                            'model_type': 'multinomial_count_vect',
                            'vectorizer': {'min_df': 7,
                                           'ngram_range': (1, 2),
                                           'stop_words': 'english'}}},
 'confusion': [[7962, 77, 50], [166, 4190, 431], [67, 502, 4133]],
 'macro_f1': 0.9140396829636389,
 'model_type': 'voting'}

In [34]:
# NOTE: this is shows some easy ways to load a model and train it.
# I was lazy and didn't actually save the models (worse case was like 5 minutes to train.)
best_config = ngram_to_tuple(load_best_config('data/experiments'))
pprint.pprint(best_config, sort_dicts=False)
model = make_model_pipeline(best_config['config'])
model

{'model_type': 'voting',
 'config': {'model_type': 'voting',
            'logistic': {'model_type': 'logistic_with_tfidf',
                         'vectorizer': {'ngram_range': (1, 2),
                                        'min_df': 10,
                                        'stop_words': 'english'},
                         'classifier': {'max_iter': 200},
                         'expressions': {'expressions': ['game|player',
                                                         'book|author|reader',
                                                         'song',
                                                         'dvd']}},
            'multinomial': {'model_type': 'multinomial_count_vect',
                            'vectorizer': {'ngram_range': (1, 2),
                                           'min_df': 7,
                                           'stop_words': 'english'},
                            'classifier': {}}},
 'macro_f1': 0.9140396829636389,
 'confusion': [[7962, 77, 50], [166, 4190, 431], [67, 502, 4133]]}

StackingClassifier(estimators=[('multinomial',
                                Pipeline(steps=[('preprocessor',
                                                 CountVectorizer(min_df=7,
                                                                 ngram_range=(1,
                                                                              2),
                                                                 stop_words='english')),
                                                ('classifier',
                                                 MultinomialNB())])),
                               ('logistic',
                                Pipeline(steps=[('features',
                                                 FeatureUnion(transformer_list=[('text',
                                                                                 TfidfVectorizer(min_df=10,
                                                                                                 ngram_range=(1,
                                                                                                              2),
                                                                                                 stop_words='english')),
                                                                                ('expressions',
                                                                                 ExpressionTransformer(expressions=['game|player',
                                                                                                                    'book|author|reader',
                                                                                                                    'song',
                                                                                                                    'dvd']))])),
                                                ('clf',
                                                 LogisticRegression(max_iter=200))]))],
                   final_estimator=LogisticRegression())

In [35]:
model.fit(df.text, df.label)

StackingClassifier(estimators=[('multinomial',
                                Pipeline(steps=[('preprocessor',
                                                 CountVectorizer(min_df=7,
                                                                 ngram_range=(1,
                                                                              2),
                                                                 stop_words='english')),
                                                ('classifier',
                                                 MultinomialNB())])),
                               ('logistic',
                                Pipeline(steps=[('features',
                                                 FeatureUnion(transformer_list=[('text',
                                                                                 TfidfVectorizer(min_df=10,
                                                                                                 ngram_range=(1,
                                                                                                              2),
                                                                                                 stop_words='english')),
                                                                                ('expressions',
                                                                                 ExpressionTransformer(expressions=['game|player',
                                                                                                                    'book|author|reader',
                                                                                                                    'song',
                                                                                                                    'dvd']))])),
                                                ('clf',
                                                 LogisticRegression(max_iter=200))]))],
                   final_estimator=LogisticRegression())

In [37]:
submission = test_data.assign(LABEL=model.predict(test_data.text)).rename(columns={'id': 'ID'})

In [39]:
submission.shape[0] == 17580

True

In [ ]:
sumbission[['ID', 'LABEL']].to_csv('submission.csv', index=False)